name: Deploy Next.js to Azure Web App (Windows)

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      # Optional: Export static site if you're using `next export`
      # - name: Export Static Site
      #   run: npm run export

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: swimming-lms  # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
